Add `--binning`, `--zoomify` and `--balancing` arguments to pipeline
koszullab/hicstuff pull request #76
Opened 2023-08-21 22:25 UTC by js2264

- `--binning INT`: when `--mat_fmt cool`, a **binned** cool matrix can also be generated from pairs file;
- `--zoomify`: if added (and `--binning INT` is present), the binned matrix will be zoomified at `binning` * [1, 2, 5, 10, 20, 50, 100] and balanced
- `--balancing STR` if zoomify, the balancing options for the .mcool file can be specified (cooler default used by default)

So the suggested pipeline call could be something like: 

```{sh}
hicstuff pipeline \
    --enzyme "DpnII,HinfI" \
    --matfmt cool  --binning=1000 --zoomify --balancing "--cis-only" \
    --genome <REF> \
    <R1> <R2>
```

I'm very tempted to change the default `matfmt` to "cool"...

2023-08-21 22:26 UTC, js2264 commented
**Note:** I added `cooler` to the `requirements.txt`... I hope this is ok?

2023-08-23 08:04 UTC, cmdoret commented
> **Note:** I added `cooler` to the `requirements.txt`... I hope this is ok?

It's currently listed in the [extras_require](https://github.com/koszullab/hicstuff/blob/ef278d2bca7c14fd7402bcc009b7e9fab7f92efa/setup.py#L67) (i.e. optional dependency) since at the time we did not use it as the main format.

I think it would make sense to make it a mandatory dependency, but then it should be removed from the `extras_require`.

2023-08-23 09:09 UTC, cmdoret requested changes
Awesome improvements!! I spotted a mistake and left a few suggestions :)

2023-08-23 09:09 UTC, cmdoret commented on hicstuff/commands.py
> +                 [--binning=INT] [--zoomify] [--balancing=STR] [--quality-min=30]
Or maybe even remove enzyme, and only use it in cutsite. What do you think @ABignaud ?

2023-08-23 09:56 UTC, js2264 commented on hicstuff/commands.py
> +                 [--binning=INT] [--zoomify] [--balancing=STR] [--quality-min=30]
> Or maybe even remove enzyme, and only use it in cutsite. What do you think @ABignaud ?

We most likely should keep `enzyme`, AFAIU the filtering depends on it.

> If we're adding a "binning" argument, should we disallow integers in `enzyme`?

Also, I believe `enzyme=100` is used for mnase/dnaseC, no? So probably best to still allow integers

2023-08-23 10:05 UTC, js2264 commented
@cmdoret thanks for your review, I've replied to your comments. Let's wait for @ABignaud input on `emzyme`

2023-08-23 11:00 UTC, cmdoret commented on hicstuff/pipeline.py
> +        sp.call(cooler_cmd.format(**cool_args), shell=True)
I made a mistake: You can actually have spaces in the value, I think the values will just be quoted automatically.

2023-08-23 17:39 UTC, js2264 commented on hicstuff/pipeline.py
> +        sp.call(cooler_cmd.format(**cool_args), shell=True)
Fixed in [749c895](https://github.com/koszullab/hicstuff/pull/76/commits/749c895c1f2f2de093293cd47bfc2597156b4967)

2023-08-24 17:39 UTC, js2264 commented on hicstuff/commands.py
> +                 [--binning=INT] [--zoomify] [--balancing=STR] [--quality-min=30]
Ok we'll keep allowing integers for `enzyme` for now

2023-08-24 17:39 UTC, merged